version: '3'
services:

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ukol
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  migrate:
    extends:
      file: docker-compose.base.yml
      service: base
    command: yarn prisma migrate dev
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/ukol
    depends_on:
      - db

  app:
    extends:
      file: docker-compose.base.yml
      service: base
    command: yarn nx serve api --host=0.0.0.0
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/ukol
    depends_on:
      - db
      - migrate

  web:
    extends:
      file: docker-compose.base.yml
      service: base
    command: yarn nx serve web --host=0.0.0.0
    ports:
      - 8080:8080
    environment:
      - GQL=https://localhost:3333/graphql
      - API=http://localhost:3333/api
    depends_on:
      - app

volumes:
  node-modules: null
  db:
    driver: local