version: '3'
services:
  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elevatorian
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
    driver: local